source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Abracadabra' do
  pod "Abracadabra", :path => "../"
end

target 'Tests' do
  pod "Abracadabra", :path => "../"
  pod 'Kiwi'
end
