language: objective-c
xcode_workspace: Example/Abracadabra.xcworkspace
xcode_scheme: Abracadabra
xcode_sdk: iphonesimulator8.1

before_install: 
- brew update
- brew unlink xctool
- brew install xctool
- pod install